---
# apps/linode_helpers/roles/certbot_ssl/tasks/main.yml
# import some DNS propagation task before getting cert

- name: check for acme test server
  shell: nc -nvz 127.0.0.1 14000 2>&1 || /bin/true
  register: test_server
  tags: test

- name: set certbot config path
  set_fact:
    config_file: /etc/letsencrypt/deploy-cli.ini
    cacheable: yes

- name: install apache certbot plugin
  include_tasks:
    file: apache-certbot.yml
  when: webserver_stack == 'lamp'

- name: install nginx certbot plugin
  include_tasks:
    file: nginx-certbot.yml
  when: webserver_stack == 'lemp'

- name: install certbot standalone plugin
  include_tasks:
    file: standalone-certbot.yml
  when: webserver_stack == 'standalone'

- name: install certbot standalone plugin
  include_tasks:
    file: standalone-certbot.yml

- name: certbot command
  set_fact:
    certbot_cmd: '{{ prefix }} {{ cmd }}'

- name: write certbot config file
  template:
    src: templates/cli.ini.j2
    dest: '{{ config_file }}'
    owner: root
    group: root
    mode: '0644'

# certbot dry-runs
- name: run dry-run for domains
  shell: '{{ certbot_cmd }} --dry-run'
  register: dry_run
  until: dry_run is not failed
  retries: 3
  delay: 3
  ignore_errors: true

# assert that we can get valid certs. Otherwise fail - can't achieve final state
- name: validate certbot dry-run
  assert:
    that: dry_run is not failed
    fail_msg: "[Error] Certbot dry-run domain. Please check /var/log/letsencrypt/letsencrypt.log"
    success_msg: "[Info] Certbot dry-run successful!"
  run_once: true

# get certs
- name: install live certificate
  shell: '{{ certbot_cmd }}'
