---
# apps/linode_helpers/roles/certbot_ssl/tasks/apache-certbot.yml
- name: install python3-certbot
  apt:
    name: python3-certbot
    state: present

- name: set certbot plugin
  set_fact:
    certbot_plugin: standalone
    prefix: REQUESTS_CA_BUNDLE={{ ca_bundle | default(omit) }}
    naw: REQUESTS_CA_BUNDLE={{ ca_bundles | default(omit) }}
    cmd: certbot certonly --config {{ config_file }} --dry-run -vvv
    # prefix: '{% if ca_bundle %}REQUESTS_CA_BUNDLE="{{ ca_bundle }}"{% endif %} '
    cacheable: yes

- name: print prefix
  debug:
    var: prefix

- name: certbot command
  set_fact:
    certbot_cmd: '{{ prefix }} {{ cmd }}'

- name: print certbot command
  debug:
    var: certbot_cmd

- name: write certbot config file
  template:
    src: templates/cli.ini.j2
    dest: '{{ config_file }}'
    owner: root
    group: root
    mode: '0644'

# - name: build certbot command
#   set_fact:
    
# certbot dry-runs
- name: run dry-run for subdomain
  shell: |-
    echo TEST
    echo "REQUESTS_CA_BUNDLE is: ${REQUESTS_CA_BUNDLE}"
    echo "config file is:"
    echo "-----"
    cat {{ config_file }}
    echo "now trying certbot"
    {{ certbot_cmd }}
    # certbot certonly --config {{ config_file }} --dry-run -vvv
  register: dry_run
  until: dry_run is not failed
  retries: 3
  delay: 3
  ignore_errors: true
  environment:
    REQUESTS_CA_BUNDLE: '{% if ca_bundle %}{{ ca_bundle }}{% endif %}'

# assert that we can get valid certs. Otherwise fail - can't achieve final state
- name: validate certbot dry-run
  assert:
    that: dry_run is not failed
    fail_msg: "[Error] Certbot dry-run domain. Please check /var/log/letsencrypt/letsencrypt.log"
    success_msg: "[Info] Certbot dry-run successful!"
  run_once: true

# get certs
- name: install live certificate
  shell: certbot certonly --config {{ config_file }}
  environment:
    REQUESTS_CA_BUNDLE: '{% if ca_bundle %}{{ ca_bundle }}{% endif %}'
