name: antmedia-test

on:
  push:
    branches:
      - main
      - develop
      - antmedia-ci
    # paths:
    #   - 'apps/linode-marketplace-antmedia-community/**'
    #   - 'deployment_scripts/linode-marketplace-antmedia-community/**'
    #   - '!apps/linode-marketplace-antmedia-community/README.md'
  pull_request:
      # paths:
      #   - 'apps/linode-marketplace-antmedia-community/**'
      #   - 'deployment_scripts/linode-marketplace-antmedia-community/**'
      #   - '!apps/linode-marketplace-antmedia-community/README.md'
  workflow_dispatch:

jobs:
  certbot:
    uses: ./.github/workflows/helpers/certbot.yml
    with:
      domain:
      subdomain:
      soa-email:

  build:
    strategy:
      matrix:
        version:
          - antmedia
          - antmedia-community
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    uses: ./.github/workflows/helpers.yml
    with:
      certbot: true

    uses: ./.github/workflows/test.yml
    with:
      app-name: ${{ matrix.version }}
      platform: ${{ matrix.os }}
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #     with:
    #       fetch-depth: 1

      # - uses: ./.github/workflows/test.yml
      #   with:
      #     app-name: ${{ matrix.version }}
      #     platform: ${{ matrix.os }}

     